### ISSUE TITLE
🐛 - No prefix in the mapping result

### ISSUE THREAD

**Issue by jatoledo** [oeg-upm/yatter#10]
[gtfs-csv-noselfjoin.yml](https://github.com/oeg-upm/kgc-eval/blob/master/mappings/gtfs-csv-noselfjoin.yml)
```yaml
prefixes:
  rr: http://www.w3.org/ns/r2rml#
  foaf: http://xmlns.com/foaf/0.1/
  xsd: http://www.w3.org/2001/XMLSchema#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  dc: http://purl.org/dc/elements/1.1/
  rev: http://purl.org/stuff/rev#
  gtfs: http://vocab.gtfs.org/terms#
  geo: http://www.w3.org/2003/01/geo/wgs84_pos#
  schema: http://schema.org/
  dct: http://purl.org/dc/terms/
  rml: http://semweb.mmlab.be/ns/rml#
  ql: http://semweb.mmlab.be/ns/ql#
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#

mappings:
  stoptimes:

```

results:
```xml
../../kgc-eval/mappings/gtfs-csv-noselfjoin.yml
------------------------START RML-------------------------------
<#stoptimes_0> a rr:TriplesMap;

        rml:logicalSource [
                a rml:logicalSource;
                rml:source /data/STOP_TIMES;
                rml:referenceFormulation ql:csv
        ];

```
