### ISSUE TITLE
🐛 Mapping error- missing square brackets

### ISSUE THREAD

**Issue by jatoledo** [oeg-upm/yatter#12]
```yml
 
mappings:
   agency:
    sources:
      - [/data/csv/1/AGENCY.csv~csv]
    s: http://transport.linkeddata.es/madrid/agency/$(agency_id)
    po:
      - [a, gtfs:Agency]
      - [foaf:page, $(agency_url)~iri]
      - [foaf:name,$(agency_name)]
```

```sql
<#agency_0> a rr:TriplesMap;

        rml:logicalSource [
                a rml:logicalSource;
                rml:source "/data/csv/1/AGENCY.csv";
                rml:referenceFormulation ql:csv
        ];
        rr:subjectMap [
                a rr:SubjectMap;
                rr:template "http://transport.linkeddata.es/madrid/agency/{agency_id}"
        ];

        rr:predicateObjectMap [
                a rr:PredicateObjectMap;
                rr:predicate rdf:type;
                rr:objectMap [
                        a rr:ObjectMap;
                        rml:reference gtfs:Agency
                ]
        ];

        rr:predicateObjectMap [
                a rr:PredicateObjectMap;
                rr:predicate foaf:page;
                rr:objectMap [
                        a rr:ObjectMap;
                        rml:reference "agency_url";
                        rr:TermType rr:IRI
                ];
                               <-----------------------------------  ****************** HERE ******************
        rr:predicateObjectMap [
                a rr:PredicateObjectMap;
                rr:predicate foaf:name;
                rr:objectMap [
                        a rr:ObjectMap;
                        rml:reference "agency_name"
                ]
        ].

```
