### ISSUE TITLE
Put quotation marks at the source and format of the file.

### ISSUE THREAD

**Issue by jatoledo** [oeg-upm/yatter#9]
```yaml
mappings:
  stoptimes:
    sources:
      - [/data/STOP_TIMES.csv~csv]
```

```bash
rml:source /data/STOP_TIMES; -------------------> rml:source "/data/STOP_TIMES.csv";
```
